site_name: CloudB Documentation
nav:
  - 'index.md'
  - 'introduction.md'
  - 'getting-started.md'
  - 'eolyse.md'
  - 'acmonitor-connect.md'
  - 'toolbox.md'
  - 'troubleshooting.md'
  - 'release-note.md'
theme:
  name: readthedocs